# Release labels (for automatic versioning)
- name: release:major
  color: "e11d21"
  description: "Breaking changes - will bump major version (x.0.0)"

- name: release:minor
  color: "fbca04"
  description: "New features - will bump minor version (0.x.0)"

- name: release:patch
  color: "0e8a16"
  description: "Bug fixes and small changes - will bump patch version (0.0.x)"

# Type labels
- name: bug
  color: "d73a4a"
  description: "Something isn't working"

- name: enhancement
  color: "a2eeef"
  description: "New feature or request"

- name: documentation
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: maintenance
  color: "ffd700"
  description: "Maintenance, CI/CD, or chore work"

- name: testing
  color: "9370db"
  description: "Related to tests"

- name: dependencies
  color: "0366d6"
  description: "Pull requests that update a dependency file"
