codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

flags:
  unittests:
    paths:
      - src/langchain_fmp_data/
    carryforward: true

  integration:
    paths:
      - src/langchain_fmp_data/
    carryforward: true
