name: Block PR to Main

on:
  pull_request:
    branches: [main]

jobs:
  check-pr-source:
    name: Check PR Source Branch
    runs-on: ubuntu-latest

    steps:
      - name: Check PR source branch
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"

          if [ "$SOURCE_BRANCH" = "dev" ]; then
            echo "✅ Allowing PR from dev to main - this is the correct workflow for promoting changes."
            echo ""
            echo "PR details:"
            echo "- Source branch: $SOURCE_BRANCH"
            echo "- Target branch: ${{ github.base_ref }}"
            echo "- PR number: #${{ github.event.number }}"
            exit 0
          else
            echo "❌ This repository does not allow direct pull requests to the main branch from feature branches."
            echo "Please create your pull request against the 'dev' branch instead."
            echo ""
            echo "Workflow:"
            echo "1. Create feature branch from 'dev'"
            echo "2. Make your changes"
            echo "3. Create PR to 'dev' branch"
            echo "4. After review and merge to 'dev', create PR from 'dev' to 'main'"
            echo ""
            echo "Current PR details:"
            echo "- Source branch: $SOURCE_BRANCH"
            echo "- Target branch: ${{ github.base_ref }}"
            echo "- PR number: #${{ github.event.number }}"
            exit 1
          fi
