name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: 'pip'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.4
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Set Windows environment
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "PYTHONUTF8=1" >> $env:GITHUB_ENV
        echo "PYTHON_EXECUTABLE=$((Get-Command python).Path)" >> $env:GITHUB_ENV
        echo "PATH=$env:USERPROFILE\.local\bin;$env:PATH" >> $env:GITHUB_ENV
        echo "POETRY_ENCODING=utf-8" >> $env:GITHUB_ENV
        # Print debug info
        Write-Host "Poetry location:"
        Get-Command poetry -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source
        Write-Host "Path environment:"
        $env:PATH -split ';' | ForEach-Object { Write-Host $_ }

    - name: Set Unix environment
      if: runner.os != 'Windows'
      run: |
        echo "PYTHON_EXECUTABLE=$(which python)" >> $GITHUB_ENV
        echo "POETRY_ENCODING=utf-8" >> $GITHUB_ENV

    - name: Load cached venv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-

    - name: Install dependencies
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        $env:PYTHONIOENCODING = "utf-8"
        # Ensure poetry is in PATH
        $poetryPath = Join-Path $env:USERPROFILE ".local" "bin" "poetry"
        if (Test-Path $poetryPath) {
            & $poetryPath env use $env:PYTHON_EXECUTABLE
            & $poetryPath install --no-interaction --with dev
        } else {
            Write-Host "Poetry not found at expected location: $poetryPath"
            Write-Host "Searching for poetry in PATH..."
            $poetryCmd = Get-Command poetry -ErrorAction SilentlyContinue
            if ($poetryCmd) {
                Write-Host "Found poetry at: $($poetryCmd.Source)"
                & $poetryCmd env use $env:PYTHON_EXECUTABLE
                & $poetryCmd install --no-interaction --with dev
            } else {
                Write-Error "Poetry not found in PATH"
                exit 1
            }
        }

    - name: Install dependencies (Unix)
      if: runner.os != 'Windows'
      run: |
        python -m pip install --upgrade pip
        poetry env use "${PYTHON_EXECUTABLE}"
        poetry install --no-interaction --with dev

    - name: List environment info
      shell: bash
      run: |
        python --version
        pip --version
        poetry --version
        poetry show
        poetry env info

    - name: Run tests
      shell: bash
      env:
        FMP_TEST_API_KEY: ${{ secrets.FMP_TEST_API_KEY }}
        PYTHONIOENCODING: utf-8
      run: |
        poetry run pytest tests/ \
          --cov=fmp_data \
          --cov-config=.coveragerc \
          --cov-report=xml \
          --cov-report=term \
          --cov-report=html \
          -v

    - name: Upload coverage
      if: runner.os == 'Linux' && matrix.python-version == '3.12'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage report
      if: runner.os == 'Linux' && matrix.python-version == '3.12'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
        if-no-files-found: error
